
---------------------------------------- CERINTA 4 - CREARE TABELE ----------------------------------------

SET SERVEROUTPUT ON;

DROP SEQUENCE SECVENTA_CLIENTI;
DROP SEQUENCE SECVENTA_ADRESE_SHOWROOM;
DROP SEQUENCE SECVENTA_MOTOARE;
DROP SEQUENCE SECVENTA_OPTIUNI;
DROP SEQUENCE SECVENTA_SHOWROOM;
DROP SEQUENCE SECVENTA_ANGAJATI;
DROP SEQUENCE SECVENTA_VEHICULE;
DROP SEQUENCE SECVENTA_FACTURI;
DROP SEQUENCE SECVENTA_NUMERE_TELEFON_SHOWROOM;
DROP SEQUENCE SECVENTA_NUMERE_TELEFON_CLIENT;
DROP SEQUENCE SECVENTA_SHOWROOMURI_ANGAJATI;
DROP SEQUENCE SECVENTA_VEHICULE_OPTIUNI;

CREATE SEQUENCE SECVENTA_CLIENTI START WITH 1;
CREATE SEQUENCE SECVENTA_ADRESE_SHOWROOM START WITH 1;
CREATE SEQUENCE SECVENTA_MOTOARE START WITH 1;
CREATE SEQUENCE SECVENTA_OPTIUNI START WITH 1;
CREATE SEQUENCE SECVENTA_SHOWROOM START WITH 1;
CREATE SEQUENCE SECVENTA_ANGAJATI START WITH 1;
CREATE SEQUENCE SECVENTA_VEHICULE START WITH 1;
CREATE SEQUENCE SECVENTA_FACTURI START WITH 1;
CREATE SEQUENCE SECVENTA_NUMERE_TELEFON_SHOWROOM START WITH 1;
CREATE SEQUENCE SECVENTA_NUMERE_TELEFON_CLIENT START WITH 1;
CREATE SEQUENCE SECVENTA_SHOWROOMURI_ANGAJATI START WITH 1;
CREATE SEQUENCE SECVENTA_VEHICULE_OPTIUNI START WITH 1;

DROP TABLE VEHICULE_OPTIUNI CASCADE CONSTRAINTS;
DROP TABLE SHOWROOMURI_ANGAJATI CASCADE CONSTRAINTS;
DROP TABLE NUMERE_TELEFON_CLIENTI CASCADE CONSTRAINTS;
DROP TABLE NUMERE_TELEFON_SHOWROOMURI CASCADE CONSTRAINTS;
DROP TABLE FACTURI CASCADE CONSTRAINTS;
DROP TABLE VEHICULE CASCADE CONSTRAINTS;
DROP TABLE ANGAJATI CASCADE CONSTRAINTS;
DROP TABLE SHOWROOMURI CASCADE CONSTRAINTS;
DROP TABLE OPTIUNI CASCADE CONSTRAINTS;
DROP TABLE MOTOARE CASCADE CONSTRAINTS;
DROP TABLE ADRESE_SHOWROOMURI CASCADE CONSTRAINTS;
DROP TABLE CLIENTI CASCADE CONSTRAINTS;

TRUNCATE TABLE VEHICULE_OPTIUNI;
TRUNCATE TABLE SHOWROOMURI_ANGAJATI;
TRUNCATE TABLE NUMERE_TELEFON_CLIENTI;
TRUNCATE TABLE NUMERE_TELEFON_SHOWROOMURI;
TRUNCATE TABLE FACTURI;
TRUNCATE TABLE VEHICULE;
TRUNCATE TABLE ANGAJATI;
TRUNCATE TABLE SHOWROOMURI;
TRUNCATE TABLE OPTIUNI;
TRUNCATE TABLE MOTOARE;
TRUNCATE TABLE ADRESE_SHOWROOMURI;
TRUNCATE TABLE CLIENTI;


CREATE TABLE CLIENTI (
    ID_CLIENT NUMBER(6) PRIMARY KEY,
    NUME VARCHAR2(256)
);

CREATE TABLE ADRESE_SHOWROOMURI (
    ID_ADRESA_SHOWROOM NUMBER(6) PRIMARY KEY,    
    STRADA VARCHAR2(256),
    NUMAR NUMBER(6),
    ORAS VARCHAR2(256)
);

CREATE TABLE MOTOARE (
    ID_MOTOR NUMBER(6) PRIMARY KEY,
    MARCA VARCHAR2(256),
    MODEL VARCHAR2(256),
    CAI_PUTERE NUMBER(6),
    CAPACITATE_CILINDRICA NUMBER(6),
    CONSUM_MEDIU NUMBER(6),
    ASPIRATIE VARCHAR2(256),
    CARBURANT VARCHAR2(256)
);

CREATE TABLE OPTIUNI (
    ID_OPTIUNE NUMBER(6) PRIMARY KEY,
    NUME VARCHAR2(256),
    PRET NUMBER(6)
);

CREATE TABLE SHOWROOMURI (
    ID_SHOWROOM NUMBER(6) PRIMARY KEY,
    ID_ADRESA NUMBER(6),
    NUME VARCHAR2(256),
    FOREIGN KEY (ID_ADRESA) REFERENCES ADRESE_SHOWROOMURI(ID_ADRESA_SHOWROOM)
);

CREATE TABLE ANGAJATI (
    ID_ANGAJAT NUMBER(6) PRIMARY KEY,
    NUME VARCHAR2(256),
    DATA_ANGAJARE DATE,
    SALARIU NUMBER(6)
);

CREATE TABLE VEHICULE (
    ID_VEHICUL NUMBER(6) PRIMARY KEY,
    ID_MOTOR NUMBER(6),
    ID_SHOWROOM NUMBER(6),
    ID_CLIENT NUMBER(6),
    MARCA VARCHAR2(256),
    MODEL VARCHAR2(256),
    AN_FABRICATIE NUMBER(6),
    PRET NUMBER(6),
    FOREIGN KEY (ID_MOTOR) REFERENCES MOTOARE(ID_MOTOR),
    FOREIGN KEY (ID_SHOWROOM) REFERENCES SHOWROOMURI(ID_SHOWROOM),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTI(ID_CLIENT),
    CONSTRAINT CHECK_ID_CLIENT_SHOWROOM CHECK (
        (ID_CLIENT IS NULL AND ID_SHOWROOM IS NOT NULL) 
        OR (ID_CLIENT IS NOT NULL AND ID_SHOWROOM IS NULL)
        OR (ID_CLIENT IS NULL AND ID_SHOWROOM IS NULL)
    )
);

CREATE TABLE FACTURI (
    ID_FACTURA NUMBER(6) PRIMARY KEY,
    ID_CLIENT NUMBER(6) NOT NULL,
    ID_ANGAJAT NUMBER(6) NOT NULL,
    ID_VEHICUL NUMBER(6) NOT NULL,
    DATA_FACTURA DATE,
    SUMA NUMBER(6),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTI(ID_CLIENT),
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJATI(ID_ANGAJAT),
    FOREIGN KEY (ID_VEHICUL) REFERENCES VEHICULE(ID_VEHICUL)
);

CREATE TABLE NUMERE_TELEFON_SHOWROOMURI (
    ID_NUMAR_TELEFON_SHOWROOM NUMBER(6) PRIMARY KEY,
    ID_SHOWROOM NUMBER(6),
    NUMAR_TELEFON VARCHAR2(256),
    CONSTRAINT CHECK_NUMAR_TELEFON_SHOWROOM CHECK
    (
        REGEXP_LIKE(NUMAR_TELEFON, '^07[0-9]{2} [0-9]{3} [0-9]{3}$')
    ),
    FOREIGN KEY (ID_SHOWROOM) REFERENCES SHOWROOMURI(ID_SHOWROOM)
);

CREATE TABLE NUMERE_TELEFON_CLIENTI (
    ID_NUMAR_TELEFON_CLIENT NUMBER(6) PRIMARY KEY,
    ID_CLIENT NUMBER(6),
    NUMAR_TELEFON VARCHAR2(256),
    CONSTRAINT CHECK_NUMAR_TELEFON_CLIENT CHECK
    (
        REGEXP_LIKE(NUMAR_TELEFON, '^07[0-9]{2} [0-9]{3} [0-9]{3}$')
    ),
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTI(ID_CLIENT)
);

CREATE TABLE SHOWROOMURI_ANGAJATI (
    ID_SHOWROOM NUMBER(6),
    ID_ANGAJAT NUMBER(6),
    PROGRAM VARCHAR2(256),
    PRIMARY KEY (ID_SHOWROOM, ID_ANGAJAT),
    FOREIGN KEY (ID_SHOWROOM) REFERENCES SHOWROOMURI(ID_SHOWROOM),
    FOREIGN KEY (ID_ANGAJAT) REFERENCES ANGAJATI(ID_ANGAJAT)
);

CREATE TABLE VEHICULE_OPTIUNI (
    ID_VEHICUL NUMBER(6),
    ID_OPTIUNE NUMBER(6),
    PRIMARY KEY (ID_VEHICUL, ID_OPTIUNE),
    FOREIGN KEY (ID_VEHICUL) REFERENCES VEHICULE(ID_VEHICUL),
    FOREIGN KEY (ID_OPTIUNE) REFERENCES OPTIUNI(ID_OPTIUNE)
);

---------------------------------------- CERINTA 5 - POPULARE TABELE ----------------------------------------

INSERT INTO CLIENTI (ID_CLIENT, NUME) VALUES (SECVENTA_CLIENTI.NEXTVAL, 'Ion Popescu');
INSERT INTO CLIENTI (ID_CLIENT, NUME) VALUES (SECVENTA_CLIENTI.NEXTVAL, 'Maria Ionescu');
INSERT INTO CLIENTI (ID_CLIENT, NUME) VALUES (SECVENTA_CLIENTI.NEXTVAL, 'Vasile Georgescu');
INSERT INTO CLIENTI (ID_CLIENT, NUME) VALUES (SECVENTA_CLIENTI.NEXTVAL, 'Elena Mihai');
INSERT INTO CLIENTI (ID_CLIENT, NUME) VALUES (SECVENTA_CLIENTI.NEXTVAL, 'Cristina Stoica');
-- INSERT INTO CLIENTI (ID_CLIENT, NUME) VALUES (SECVENTA_CLIENTI.NEXTVAL, 'Andrei Dumitru');
-- INSERT INTO CLIENTI (ID_CLIENT, NUME) VALUES (SECVENTA_CLIENTI.NEXTVAL, 'Daniela Marin');
-- INSERT INTO CLIENTI (ID_CLIENT, NUME) VALUES (SECVENTA_CLIENTI.NEXTVAL, 'Mihai Petrescu');
-- INSERT INTO CLIENTI (ID_CLIENT, NUME) VALUES (SECVENTA_CLIENTI.NEXTVAL, 'Oana Radu');
-- INSERT INTO CLIENTI (ID_CLIENT, NUME) VALUES (SECVENTA_CLIENTI.NEXTVAL, 'Alexandru Baciu');

INSERT INTO ADRESE_SHOWROOMURI (ID_ADRESA_SHOWROOM, STRADA, NUMAR, ORAS) VALUES (SECVENTA_ADRESE_SHOWROOM.NEXTVAL, 'Soseaua Colentina', 33, 'Bucuresti');
INSERT INTO ADRESE_SHOWROOMURI (ID_ADRESA_SHOWROOM, STRADA, NUMAR, ORAS) VALUES (SECVENTA_ADRESE_SHOWROOM.NEXTVAL, 'Strada Republicii', 45, 'Cluj-Napoca');
INSERT INTO ADRESE_SHOWROOMURI (ID_ADRESA_SHOWROOM, STRADA, NUMAR, ORAS) VALUES (SECVENTA_ADRESE_SHOWROOM.NEXTVAL, 'Bulevardul Basarabia', 34, 'Bucuresti');
INSERT INTO ADRESE_SHOWROOMURI (ID_ADRESA_SHOWROOM, STRADA, NUMAR, ORAS) VALUES (SECVENTA_ADRESE_SHOWROOM.NEXTVAL, 'Strada Unirii', 23, 'Timisoara');
INSERT INTO ADRESE_SHOWROOMURI (ID_ADRESA_SHOWROOM, STRADA, NUMAR, ORAS) VALUES (SECVENTA_ADRESE_SHOWROOM.NEXTVAL, 'Strada Libertatii', 56, 'Constanta');
INSERT INTO ADRESE_SHOWROOMURI (ID_ADRESA_SHOWROOM, STRADA, NUMAR, ORAS) VALUES (SECVENTA_ADRESE_SHOWROOM.NEXTVAL, 'Strada Independentei', 78, 'Craiova');
INSERT INTO ADRESE_SHOWROOMURI (ID_ADRESA_SHOWROOM, STRADA, NUMAR, ORAS) VALUES (SECVENTA_ADRESE_SHOWROOM.NEXTVAL, 'Strada Victoriei', 89, 'Brasov');
INSERT INTO ADRESE_SHOWROOMURI (ID_ADRESA_SHOWROOM, STRADA, NUMAR, ORAS) VALUES (SECVENTA_ADRESE_SHOWROOM.NEXTVAL, 'Strada Mihai Viteazu', 101, 'Galati');
INSERT INTO ADRESE_SHOWROOMURI (ID_ADRESA_SHOWROOM, STRADA, NUMAR, ORAS) VALUES (SECVENTA_ADRESE_SHOWROOM.NEXTVAL, 'Strada Stefan cel Mare', 67, 'Ploiesti');
INSERT INTO ADRESE_SHOWROOMURI (ID_ADRESA_SHOWROOM, STRADA, NUMAR, ORAS) VALUES (SECVENTA_ADRESE_SHOWROOM.NEXTVAL, 'Strada Tudor Vladimirescu', 34, 'Oradea');

INSERT INTO MOTOARE (ID_MOTOR, MARCA, MODEL, CAI_PUTERE, CAPACITATE_CILINDRICA, CONSUM_MEDIU, ASPIRATIE, CARBURANT) 
VALUES (SECVENTA_MOTOARE.NEXTVAL, 'Renault', 'K9K', 110, 1461, 4.8, 'Turbo', 'Diesel');
INSERT INTO MOTOARE (ID_MOTOR, MARCA, MODEL, CAI_PUTERE, CAPACITATE_CILINDRICA, CONSUM_MEDIU, ASPIRATIE, CARBURANT) 
VALUES (SECVENTA_MOTOARE.NEXTVAL, 'Renault', 'H5Ft', 140, 1333, 5.3, 'Turbo', 'Benzina');
INSERT INTO MOTOARE (ID_MOTOR, MARCA, MODEL, CAI_PUTERE, CAPACITATE_CILINDRICA, CONSUM_MEDIU, ASPIRATIE, CARBURANT) 
VALUES (SECVENTA_MOTOARE.NEXTVAL, 'Renault', 'F4R', 170, 1998, 7.5, 'Natural', 'Benzina');
INSERT INTO MOTOARE (ID_MOTOR, MARCA, MODEL, CAI_PUTERE, CAPACITATE_CILINDRICA, CONSUM_MEDIU, ASPIRATIE, CARBURANT) 
VALUES (SECVENTA_MOTOARE.NEXTVAL, 'Renault', 'M9R', 150, 1995, 6.0, 'Turbo', 'Diesel');
INSERT INTO MOTOARE (ID_MOTOR, MARCA, MODEL, CAI_PUTERE, CAPACITATE_CILINDRICA, CONSUM_MEDIU, ASPIRATIE, CARBURANT) 
VALUES (SECVENTA_MOTOARE.NEXTVAL, 'Dacia', 'K7M', 90, 1598, 7.0, 'Natural', 'Benzina');
INSERT INTO MOTOARE (ID_MOTOR, MARCA, MODEL, CAI_PUTERE, CAPACITATE_CILINDRICA, CONSUM_MEDIU, ASPIRATIE, CARBURANT) 
VALUES (SECVENTA_MOTOARE.NEXTVAL, 'Dacia', 'K4M', 105, 1598, 6.5, 'Natural', 'Benzina');
INSERT INTO MOTOARE (ID_MOTOR, MARCA, MODEL, CAI_PUTERE, CAPACITATE_CILINDRICA, CONSUM_MEDIU, ASPIRATIE, CARBURANT) 
VALUES (SECVENTA_MOTOARE.NEXTVAL, 'Dacia', 'H4Bt', 130, 1332, 5.8, 'Turbo', 'Benzina');
INSERT INTO MOTOARE (ID_MOTOR, MARCA, MODEL, CAI_PUTERE, CAPACITATE_CILINDRICA, CONSUM_MEDIU, ASPIRATIE, CARBURANT) 
VALUES (SECVENTA_MOTOARE.NEXTVAL, 'Renault', 'R9M', 130, 1598, 4.5, 'Turbo', 'Diesel');
INSERT INTO MOTOARE (ID_MOTOR, MARCA, MODEL, CAI_PUTERE, CAPACITATE_CILINDRICA, CONSUM_MEDIU, ASPIRATIE, CARBURANT) 
VALUES (SECVENTA_MOTOARE.NEXTVAL, 'Dacia', 'H5Ht', 150, 1332, 5.5, 'Turbo', 'Benzina');
INSERT INTO MOTOARE (ID_MOTOR, MARCA, MODEL, CAI_PUTERE, CAPACITATE_CILINDRICA, CONSUM_MEDIU, ASPIRATIE, CARBURANT) 
VALUES (SECVENTA_MOTOARE.NEXTVAL, 'Renault', 'K4J', 75, 1390, 6.8, 'Natural', 'Benzina');

INSERT INTO OPTIUNI (ID_OPTIUNE, NUME, PRET) VALUES (SECVENTA_OPTIUNI.NEXTVAL, 'Navigatie', 1200);
INSERT INTO OPTIUNI (ID_OPTIUNE, NUME, PRET) VALUES (SECVENTA_OPTIUNI.NEXTVAL, 'Scaune incalzite', 800);
INSERT INTO OPTIUNI (ID_OPTIUNE, NUME, PRET) VALUES (SECVENTA_OPTIUNI.NEXTVAL, 'Climatizare automata', 1500);
INSERT INTO OPTIUNI (ID_OPTIUNE, NUME, PRET) VALUES (SECVENTA_OPTIUNI.NEXTVAL, 'Sistem audio premium', 1000);
INSERT INTO OPTIUNI (ID_OPTIUNE, NUME, PRET) VALUES (SECVENTA_OPTIUNI.NEXTVAL, 'Faruri LED', 900);
INSERT INTO OPTIUNI (ID_OPTIUNE, NUME, PRET) VALUES (SECVENTA_OPTIUNI.NEXTVAL, 'Senzori parcare', 600);
INSERT INTO OPTIUNI (ID_OPTIUNE, NUME, PRET) VALUES (SECVENTA_OPTIUNI.NEXTVAL, 'Camera marsarier', 700);
INSERT INTO OPTIUNI (ID_OPTIUNE, NUME, PRET) VALUES (SECVENTA_OPTIUNI.NEXTVAL, 'Pilot automat', 1100);
INSERT INTO OPTIUNI (ID_OPTIUNE, NUME, PRET) VALUES (SECVENTA_OPTIUNI.NEXTVAL, 'Jante aliaj', 1300);
INSERT INTO OPTIUNI (ID_OPTIUNE, NUME, PRET) VALUES (SECVENTA_OPTIUNI.NEXTVAL, 'Trapa panoramica', 2000);

INSERT INTO SHOWROOMURI (ID_SHOWROOM, ID_ADRESA, NUME) 
VALUES (SECVENTA_SHOWROOM.NEXTVAL, 1, 'Dacia Bucuresti Colentina');
INSERT INTO SHOWROOMURI (ID_SHOWROOM, ID_ADRESA, NUME) 
VALUES (SECVENTA_SHOWROOM.NEXTVAL, 2, 'Dacia Cluj-Napoca');
INSERT INTO SHOWROOMURI (ID_SHOWROOM, ID_ADRESA, NUME) 
VALUES (SECVENTA_SHOWROOM.NEXTVAL, 3, 'Dacia Bucuresti Basarabiei');
INSERT INTO SHOWROOMURI (ID_SHOWROOM, ID_ADRESA, NUME) 
VALUES (SECVENTA_SHOWROOM.NEXTVAL, 4, 'Dacia Timisoara');
INSERT INTO SHOWROOMURI (ID_SHOWROOM, ID_ADRESA, NUME) 
VALUES (SECVENTA_SHOWROOM.NEXTVAL, 5, 'Dacia Constanta');
-- INSERT INTO SHOWROOMURI (ID_SHOWROOM, ID_ADRESA, NUME) 
-- VALUES (SECVENTA_SHOWROOM.NEXTVAL, 6, 'Dacia Craiova');
-- INSERT INTO SHOWROOMURI (ID_SHOWROOM, ID_ADRESA, NUME) 
-- VALUES (SECVENTA_SHOWROOM.NEXTVAL, 7, 'Dacia Brasov');
-- INSERT INTO SHOWROOMURI (ID_SHOWROOM, ID_ADRESA, NUME) 
-- VALUES (SECVENTA_SHOWROOM.NEXTVAL, 8, 'Dacia Galati');
-- INSERT INTO SHOWROOMURI (ID_SHOWROOM, ID_ADRESA, NUME) 
-- VALUES (SECVENTA_SHOWROOM.NEXTVAL, 9, 'Dacia Ploiesti');
-- INSERT INTO SHOWROOMURI (ID_SHOWROOM, ID_ADRESA, NUME) 
-- VALUES (SECVENTA_SHOWROOM.NEXTVAL, 10, 'Dacia Oradea');

INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, DATA_ANGAJARE, SALARIU) 
VALUES (SECVENTA_ANGAJATI.NEXTVAL, 'Vasile Ion', TO_DATE('2020-01-15', 'YYYY-MM-DD'), 3500);
INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, DATA_ANGAJARE, SALARIU) 
VALUES (SECVENTA_ANGAJATI.NEXTVAL, 'Mihai Ana', TO_DATE('2019-06-10', 'YYYY-MM-DD'), 4200);
INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, DATA_ANGAJARE, SALARIU) 
VALUES (SECVENTA_ANGAJATI.NEXTVAL, 'Popa George', TO_DATE('2018-03-20', 'YYYY-MM-DD'), 3800);
INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, DATA_ANGAJARE, SALARIU) 
VALUES (SECVENTA_ANGAJATI.NEXTVAL, 'Ionescu Maria', TO_DATE('2021-11-05', 'YYYY-MM-DD'), 3100);
INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, DATA_ANGAJARE, SALARIU) 
VALUES (SECVENTA_ANGAJATI.NEXTVAL, 'Dumitrescu Andrei', TO_DATE('2017-09-12', 'YYYY-MM-DD'), 4500);
INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, DATA_ANGAJARE, SALARIU) 
VALUES (SECVENTA_ANGAJATI.NEXTVAL, 'Stoian Cristina', TO_DATE('2022-02-28', 'YYYY-MM-DD'), 3300);
INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, DATA_ANGAJARE, SALARIU) 
VALUES (SECVENTA_ANGAJATI.NEXTVAL, 'Petre Mihai', TO_DATE('2016-07-19', 'YYYY-MM-DD'), 4700);
INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, DATA_ANGAJARE, SALARIU) 
VALUES (SECVENTA_ANGAJATI.NEXTVAL, 'Radu Elena', TO_DATE('2020-05-23', 'YYYY-MM-DD'), 3600);
INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, DATA_ANGAJARE, SALARIU) 
VALUES (SECVENTA_ANGAJATI.NEXTVAL, 'Badea Alexandru', TO_DATE('2019-08-14', 'YYYY-MM-DD'), 3900);
INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, DATA_ANGAJARE, SALARIU) 
VALUES (SECVENTA_ANGAJATI.NEXTVAL, 'Marinescu Daniela', TO_DATE('2018-12-01', 'YYYY-MM-DD'), 3400);

-- VEHICULE SHOWROOM
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 1, 1, NULL, 'Dacia', 'Duster', 2024, 15000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 2, 1, NULL, 'Dacia', 'Sandero', 2024, 12000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 3, 2, NULL, 'Dacia', 'Logan', 2023, 13000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 4, 3, NULL, 'Dacia', 'Lodgy', 2024, 14000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 5, 4, NULL, 'Dacia', 'Dokker', 2024, 13500);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 6, 5, NULL, 'Dacia', 'Spring', 2024, 16000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 7, 1, NULL, 'Dacia', 'Duster', 2024, 15000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 8, 2, NULL, 'Dacia', 'Sandero', 2025, 12000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 9, 3, NULL, 'Dacia', 'Logan', 2023, 13000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 10, 4, NULL, 'Dacia', 'Lodgy', 2023, 14000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 1, 1, NULL, 'Dacia', 'Duster', 2024, 15000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 2, 1, NULL, 'Dacia', 'Sandero', 2024, 12000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 3, 2, NULL, 'Dacia', 'Logan', 2025, 13000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 4, 3, NULL, 'Dacia', 'Lodgy', 2024, 14000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 5, 4, NULL, 'Dacia', 'Dokker', 2024, 13500);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 6, 5, NULL, 'Dacia', 'Spring', 2024, 16000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 7, 1, NULL, 'Dacia', 'Duster', 2023, 15000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 8, 2, NULL, 'Dacia', 'Sandero', 2023, 12000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 9, 3, NULL, 'Dacia', 'Logan', 2024, 13000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 10, 4, NULL, 'Dacia', 'Lodgy', 2025, 14000);

-- VEHICULE CLIENTI
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 1, NULL, 1, 'Dacia', 'Duster', 2021, 15000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 2, NULL, 2, 'Dacia', 'Sandero', 2023, 12000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 3, NULL, 3, 'Dacia', 'Logan', 2023, 13000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 4, NULL, 4, 'Dacia', 'Lodgy', 2022, 14000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 5, NULL, 5, 'Dacia', 'Dokker', 2019, 13500);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 6, NULL, 1, 'Dacia', 'Spring', 2024, 16000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 7, NULL, 2, 'Dacia', 'Duster', 2024, 15000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 8, NULL, 3, 'Dacia', 'Sandero', 2022, 12000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 9, NULL, 4, 'Dacia', 'Logan', 2021, 13000);
INSERT INTO VEHICULE (ID_VEHICUL, ID_MOTOR, ID_SHOWROOM, ID_CLIENT, MARCA, MODEL, AN_FABRICATIE, PRET)
VALUES (SECVENTA_VEHICULE.NEXTVAL, 10, NULL, 1, 'Dacia', 'Lodgy', 2024, 14000);

INSERT INTO FACTURI (ID_FACTURA, ID_CLIENT, ID_ANGAJAT, ID_VEHICUL, DATA_FACTURA, SUMA)
VALUES (SECVENTA_FACTURI.NEXTVAL, 1, 1, 21, TO_DATE('2021-07-01', 'YYYY-MM-DD'), 15000);
INSERT INTO FACTURI (ID_FACTURA, ID_CLIENT, ID_ANGAJAT, ID_VEHICUL, DATA_FACTURA, SUMA)
VALUES (SECVENTA_FACTURI.NEXTVAL, 2, 2, 22, TO_DATE('2023-08-15', 'YYYY-MM-DD'), 12000);
INSERT INTO FACTURI (ID_FACTURA, ID_CLIENT, ID_ANGAJAT, ID_VEHICUL, DATA_FACTURA, SUMA)
VALUES (SECVENTA_FACTURI.NEXTVAL, 3, 3, 23, TO_DATE('2023-09-10', 'YYYY-MM-DD'), 13000);
INSERT INTO FACTURI (ID_FACTURA, ID_CLIENT, ID_ANGAJAT, ID_VEHICUL, DATA_FACTURA, SUMA)
VALUES (SECVENTA_FACTURI.NEXTVAL, 4, 4, 24, TO_DATE('2022-10-05', 'YYYY-MM-DD'), 14000);
INSERT INTO FACTURI (ID_FACTURA, ID_CLIENT, ID_ANGAJAT, ID_VEHICUL, DATA_FACTURA, SUMA)
VALUES (SECVENTA_FACTURI.NEXTVAL, 5, 5, 25, TO_DATE('2019-11-20', 'YYYY-MM-DD'), 13500);
INSERT INTO FACTURI (ID_FACTURA, ID_CLIENT, ID_ANGAJAT, ID_VEHICUL, DATA_FACTURA, SUMA)
VALUES (SECVENTA_FACTURI.NEXTVAL, 1, 6, 26, TO_DATE('2024-12-01', 'YYYY-MM-DD'), 16000);
INSERT INTO FACTURI (ID_FACTURA, ID_CLIENT, ID_ANGAJAT, ID_VEHICUL, DATA_FACTURA, SUMA)
VALUES (SECVENTA_FACTURI.NEXTVAL, 2, 7, 27, TO_DATE('2024-12-15', 'YYYY-MM-DD'), 15000);
INSERT INTO FACTURI (ID_FACTURA, ID_CLIENT, ID_ANGAJAT, ID_VEHICUL, DATA_FACTURA, SUMA)
VALUES (SECVENTA_FACTURI.NEXTVAL, 3, 8, 28, TO_DATE('2022-01-10', 'YYYY-MM-DD'), 12000);
INSERT INTO FACTURI (ID_FACTURA, ID_CLIENT, ID_ANGAJAT, ID_VEHICUL, DATA_FACTURA, SUMA)
VALUES (SECVENTA_FACTURI.NEXTVAL, 4, 1, 29, TO_DATE('2021-02-05', 'YYYY-MM-DD'), 13000);
INSERT INTO FACTURI (ID_FACTURA, ID_CLIENT, ID_ANGAJAT, ID_VEHICUL, DATA_FACTURA, SUMA)
VALUES (SECVENTA_FACTURI.NEXTVAL, 1, 1, 30, TO_DATE('2024-03-20', 'YYYY-MM-DD'), 14000);

INSERT INTO NUMERE_TELEFON_SHOWROOMURI (ID_NUMAR_TELEFON_SHOWROOM, ID_SHOWROOM, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_SHOWROOM.NEXTVAL, 1, '0725 426 589');
INSERT INTO NUMERE_TELEFON_SHOWROOMURI (ID_NUMAR_TELEFON_SHOWROOM, ID_SHOWROOM, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_SHOWROOM.NEXTVAL, 1, '0754 113 636');
INSERT INTO NUMERE_TELEFON_SHOWROOMURI (ID_NUMAR_TELEFON_SHOWROOM, ID_SHOWROOM, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_SHOWROOM.NEXTVAL, 2, '0726 214 577');
INSERT INTO NUMERE_TELEFON_SHOWROOMURI (ID_NUMAR_TELEFON_SHOWROOM, ID_SHOWROOM, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_SHOWROOM.NEXTVAL, 2, '0732 355 518');
INSERT INTO NUMERE_TELEFON_SHOWROOMURI (ID_NUMAR_TELEFON_SHOWROOM, ID_SHOWROOM, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_SHOWROOM.NEXTVAL, 3, '0727 446 289');
INSERT INTO NUMERE_TELEFON_SHOWROOMURI (ID_NUMAR_TELEFON_SHOWROOM, ID_SHOWROOM, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_SHOWROOM.NEXTVAL, 3, '0754 566 491');
INSERT INTO NUMERE_TELEFON_SHOWROOMURI (ID_NUMAR_TELEFON_SHOWROOM, ID_SHOWROOM, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_SHOWROOM.NEXTVAL, 4, '0723 638 941');
INSERT INTO NUMERE_TELEFON_SHOWROOMURI (ID_NUMAR_TELEFON_SHOWROOM, ID_SHOWROOM, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_SHOWROOM.NEXTVAL, 4, '0754 749 020');
INSERT INTO NUMERE_TELEFON_SHOWROOMURI (ID_NUMAR_TELEFON_SHOWROOM, ID_SHOWROOM, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_SHOWROOM.NEXTVAL, 5, '0739 481 395');
INSERT INTO NUMERE_TELEFON_SHOWROOMURI (ID_NUMAR_TELEFON_SHOWROOM, ID_SHOWROOM, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_SHOWROOM.NEXTVAL, 5, '0704 719 578');

INSERT INTO NUMERE_TELEFON_CLIENTI (ID_NUMAR_TELEFON_CLIENT, ID_CLIENT, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_CLIENT.NEXTVAL, 1, '0793 765 902');
INSERT INTO NUMERE_TELEFON_CLIENTI (ID_NUMAR_TELEFON_CLIENT, ID_CLIENT, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_CLIENT.NEXTVAL, 1, '0794 832 384');
INSERT INTO NUMERE_TELEFON_CLIENTI (ID_NUMAR_TELEFON_CLIENT, ID_CLIENT, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_CLIENT.NEXTVAL, 2, '0748 200 555');
INSERT INTO NUMERE_TELEFON_CLIENTI (ID_NUMAR_TELEFON_CLIENT, ID_CLIENT, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_CLIENT.NEXTVAL, 2, '0774 195 594');
INSERT INTO NUMERE_TELEFON_CLIENTI (ID_NUMAR_TELEFON_CLIENT, ID_CLIENT, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_CLIENT.NEXTVAL, 3, '0758 102 333');
INSERT INTO NUMERE_TELEFON_CLIENTI (ID_NUMAR_TELEFON_CLIENT, ID_CLIENT, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_CLIENT.NEXTVAL, 3, '0759 392 101');
INSERT INTO NUMERE_TELEFON_CLIENTI (ID_NUMAR_TELEFON_CLIENT, ID_CLIENT, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_CLIENT.NEXTVAL, 4, '0754 393 121');
INSERT INTO NUMERE_TELEFON_CLIENTI (ID_NUMAR_TELEFON_CLIENT, ID_CLIENT, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_CLIENT.NEXTVAL, 4, '0754 102 303');
INSERT INTO NUMERE_TELEFON_CLIENTI (ID_NUMAR_TELEFON_CLIENT, ID_CLIENT, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_CLIENT.NEXTVAL, 5, '0749 584 431');
INSERT INTO NUMERE_TELEFON_CLIENTI (ID_NUMAR_TELEFON_CLIENT, ID_CLIENT, NUMAR_TELEFON)
VALUES (SECVENTA_NUMERE_TELEFON_CLIENT.NEXTVAL, 5, '0755 492 120');

INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (1, 1, 'Luni-Miercuri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (1, 2, 'Luni-Vineri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (2, 3, 'Luni-Miercuri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (2, 4, 'Luni-Vineri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (3, 5, 'Luni-Miercuri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (3, 6, 'Luni-Vineri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (4, 7, 'Luni-Miercuri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (4, 8, 'Luni-Vineri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (5, 9, 'Luni-Miercuri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (5, 10, 'Luni-Vineri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (1, 3, 'Joi-Vineri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (2, 5, 'Joi-Vineri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (3, 7, 'Joi-Vineri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (4, 9, 'Joi-Vineri 9-17');
INSERT INTO SHOWROOMURI_ANGAJATI (ID_SHOWROOM, ID_ANGAJAT, PROGRAM) VALUES (5, 1, 'Joi-Vineri 9-17');

INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (11, 1);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (11, 2);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (12, 3);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (12, 4);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (13, 5);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (13, 6);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (14, 7);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (14, 8);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (15, 9);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (15, 10);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (16, 1);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (16, 2);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (17, 3);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (17, 4);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (18, 5);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (18, 6);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (19, 7);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (19, 8);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (20, 9);
INSERT INTO VEHICULE_OPTIUNI (ID_VEHICUL, ID_OPTIUNE) VALUES (20, 10);


---------------------------------------- CERINTA 6 ----------------------------------------

-- Formulați în limbaj natural o problemă pe care să o rezolvați folosind un subprogram stocat
-- independent care să utilizeze toate cele 3 tipuri de colecții studiate. Apelați subprogramul.

-- MEMORATI TOATE VEHICULELE CARE SUNT DETINUTE IN PREZENT DE CLIENTI, ADICA 
-- VEHICULE.ID_SHOWROOM == NULL AND VEHICULE.ID_CLIENT != NULL; 
-- AFISATI ACESTE VEHICULE IMPREUNA CU CLIENTUL SI FACTURA AFERENTA VANZARII

-- AFISATI PENTRU FIECARE ANGAJAT IN ORDINE DESCRESCATOARE DUPA TOTALUL SUMELOR FACTURILOR EMISE DE ACESTA:
-- - ID_ANGAJAT 
-- - TOTALUL SUMELOR FACTURILOR EMISE DE ACESTA
-- - NUMARUL DE FACTURI EMISE DE ACESTA

CREATE OR REPLACE PROCEDURE cerinta_6 IS

	TYPE tip_tablou_indexat IS TABLE OF ANGAJATI.ID_ANGAJAT%TYPE INDEX BY PLS_INTEGER;
	TYPE tip_tablou_imbricat IS TABLE OF FACTURI.SUMA%TYPE INDEX BY PLS_INTEGER;
	TYPE tip_vector is VARRAY(100) OF NUMBER(6);

	t_id_angajati tip_tablou_indexat;
	t_suma_facturi tip_tablou_imbricat;
	t_numar_facturi tip_vector := tip_vector();

	v_suma NUMBER(6) := 0;
	v_contor NUMBER(6) := 0;

	aux_id_angajat ANGAJATI.ID_ANGAJAT%TYPE;
	aux_suma_factura FACTURI.SUMA%TYPE;
	aux_numar_facturi NUMBER(6);


BEGIN

	-- ID_ANGAJATI
	SELECT
		ID_ANGAJAT
	BULK COLLECT INTO t_id_angajati
	FROM ANGAJATI;

	-- SUME FACTURI
	FOR i IN 1..t_id_angajati.COUNT LOOP

		SELECT
			NVL(SUM(SUMA), 0)
		INTO v_suma
		FROM FACTURI
		WHERE ID_ANGAJAT = t_id_angajati(i);

		t_suma_facturi(i) := v_suma;

	END LOOP;

	-- NUMAR FACTURI
	FOR i IN 1..t_id_angajati.COUNT LOOP

		SELECT
			COUNT(*)
		INTO v_contor
		FROM FACTURI
		WHERE ID_ANGAJAT = t_id_angajati(i);

		t_numar_facturi.EXTEND;
		t_numar_facturi(i) := v_contor;

	END LOOP;

	-- SORTARE DESCRESCATOR
	FOR i IN 1..t_id_angajati.COUNT LOOP
		FOR j IN i+1..t_id_angajati.COUNT LOOP
			IF t_suma_facturi(i) < t_suma_facturi(j) THEN
				
				aux_id_angajat := t_id_angajati(i);
				t_id_angajati(i) := t_id_angajati(j);
				t_id_angajati(j) := aux_id_angajat;

				aux_suma_factura := t_suma_facturi(i);
				t_suma_facturi(i) := t_suma_facturi(j);
				t_suma_facturi(j) := aux_suma_factura;

				aux_numar_facturi := t_numar_facturi(i);
				t_numar_facturi(i) := t_numar_facturi(j);
				t_numar_facturi(j) := aux_numar_facturi;

			END IF;
		END LOOP;
	END LOOP;

	-- AFISARE
	FOR i IN 1..t_id_angajati.COUNT LOOP

		DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------------');
		DBMS_OUTPUT.PUT_LINE('ID_ANGAJAT: ' || t_id_angajati(i));
		DBMS_OUTPUT.PUT_LINE('TOTALUL SUMELOR FACTURILOR EMISE DE ACESTA: ' || t_suma_facturi(i));
		DBMS_OUTPUT.PUT_LINE('NUMARUL DE FACTURI EMISE DE ACESTA: ' || t_numar_facturi(i));

	END LOOP;

END;
/

BEGIN
	cerinta_6;
END;
/
